extraction:
  cpp:
    after_prepare: 
      - python report.py 3
  cobol:
    after_prepare: 
      - python report.py 3
  csharp:
    after_prepare: 
      - python report.py 3
  java:
    after_prepare: 
      - python report.py 3
  javascript:
    after_prepare: 
      - python report.py 3
  python:
    after_prepare: 
      - python report.py 3
